# fly.toml app configuration file generated for api-node-testes on 2025-08-29T04:06:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-node-testes'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = 'pnpm run db:migrate'